### ISSUE TITLE
This is not your project

### ISSUE THREAD

**Issue by DortDev** [Stanley-GF/Shark.Solar#4]
This is my project, give me credit, i don't give a shit that you leaked it.

**Comment by DortDev** [comment]
Also, credit @h0nde for the hcaptcha stuff

**Comment by Stanley-GF** [comment]
ur insanity? and yh credit to h0nde.

**Comment by DortDev** [comment]
No, I'm dort, Aydon (Insanity) is my friend, I made the project.

**Comment by Stanley-GF** [comment]
ok cool i have to edit some things, that aight, a lot of ppl are skidding it.
